### PR TITLE
fix: temporary site popover: disable when offline

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
On the temporary site popover, disable data fetching and site creation when offline.

### Related Issues
Addresses https://github.com/techmatters/terraso-mobile-client/issues/2560

### CODE REVIEW

**Review by knipec — COMMENTED** [review]
Issue: it appears there are still backend queries being attempted when the user clicks a point on the map to bring up the temporary site popover (and therefore console errors are visible in dev builds). I feel like we should make sure to avoid any queries associated with the temporary site popover when offline.

**Review by tm-ruxandra — CHANGES_REQUESTED** [review]
PO files need to be updated, otherwise seems reasonable

**Comment by paulschreiber** [comment]
@tm-ruxandra I updated the PO files. Do I need to do additional work to ensure I'm not making calls to the soil id service when offline?

**Comment by tm-ruxandra** [comment]
@paulschreiber I think I lost track of which ticket is which - this ticket is fine standalone since it didn't cover disabling soil ID loading offline, but the other ticket (#2372) probably needs to be reworked.

**Pull request merged**
